### ISSUE TITLE
running command Install Studio Plugin causes EPERM Operation Not Permitted error

### ISSUE THREAD

**Issue by reimakesgames** [tacheometry/testez-companion#12]
![image](https://user-images.githubusercontent.com/86756689/218251614-9c851849-ec2a-4be0-ad83-eb2537504dbd.png)

i don't know what to do with this

**Comment by tacheometry** [comment]
Do you have administrator permissions?

**Comment by tacheometry** [comment]
Additionally, did you have any local plugins installed before?
